### ISSUE TITLE
http://mooc.fi/english.html with two "CyberSecurityBase"-courses

### ISSUE THREAD

**Issue by Hlynrkjaer** [moocfi/moocfi.github.io#14]
Hello,

Currently http://mooc.fi/english.html with four courses:

- Cyber Security Base with F‑Secure || Intermediate  || Ongoing;

- Object oriented programming with Java, part 1 || Beginner  || No deadlines Self-paced - start any time;

- Object oriented programming with Java, part 2 || Beginner  || No deadlines Self-paced - start any time;

- Cyber Security Base with F‑Secure || Beginner  || Ongoing Started on 31.10.2017

Both "CSB with F-Secure" pinned to http://mooc.fi/courses/2017/cybersecurity

Thanks!

**Comment by Redande** [comment]
Hey, 

Thanks for bringing this to our attention! I've removed the extra CSB with F-Secure from the course listing.
